### ISSUE TITLE
Listed.to Blog Not Sending Emails For New Subscribers or Guestbook Entries

### ISSUE THREAD

**Issue by sjc5** [standardnotes/listed#122]
Hi, I have my Listed blog set up and have tested the subscriber feature and guestbook feature, but I don't seem to get any notifications to my email address (it is set up to get notifications and be a reply email in settings).

To clarify, (1) I have an email set up in Listed settings, (2) I have tried subscribing to my own newsletter from a different email address (as well as adding faux guestbook entries) to test the notifications feature, and (3) nothing shows up in my email inbox (including spam).

**Comment by JaspalSuri** [comment]
Hi @sjc5,

While I've replied to your thread on our [Slack](https://standardnotes.org/slack), I just wanted to let you know I was able to reproduce the issue and have forwarded it for the dev team to investigate further. 🙂

**Comment by atmoio** [comment]
Emails for new subscribers should be sent (so long as your email is verified), but emails for new guestbook entries are disabled due to potential for spam abuse. Instead you'll see alerts in your Actions menu, like this:

<img width="280" alt="Screen Shot 2021-04-07 at 11 47 03 AM" src="https://user-images.githubusercontent.com/3277844/114064282-16658880-985f-11eb-8bc9-056d097b35d4.png">
